### ISSUE TITLE
choice extra_info_text is not being submitted

### ISSUE THREAD

**Issue by scattermagic** [project-callisto/django-wizard-builder#195]
No value is submitted when entering text into extra_info_text on a radio or checkbox choice.

**Comment by lynncyrin** [comment]
The conditionals (that being the term for `extra_info_text` and `ChoiceOption`s) are still very WIP, I had to stop work on them midday through implementation

**Comment by lynncyrin** [comment]
I'm going to remove all the WIP conditionals stuff today -

**Comment by lynncyrin** [comment]
closed via https://github.com/project-callisto/django-wizard-builder/pull/205
